name: main
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      name: Hello world action step
      id: hello
      uses: davidson-ncompass/gitActions
      with:
        who-to-greet: 'Davidson'
        
      #Use the output from the `Hello` step
      name: Get the output time
      run: echo "The time was ${{stes.hello.outputs.time}}"
